import Navbar from "@/component/Navbar/Navbar";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Hero from "@/component/Hero/Hero";
import CardSection from "@/pages/CardSection";
import Footer from "@/component/Footer/Footer";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className={styles.box}>
          <Hero />
          <CardSection />
          <Footer />
        </div>
      </div>
    </>
  );
}
